version: 2.1

executors:
  troubleshoot-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/project

jobs:
  analyze-support-bundle:
    executor: troubleshoot-executor
    steps:
      - checkout

      # Download, extract, and install the Troubleshoot CLI for Linux
      - run:
          name: Install Troubleshoot CLI
          command: |
            curl -LO https://github.com/replicatedhq/troubleshoot/releases/download/v0.114.0/support-bundle_linux_amd64.tar.gz
            tar -xzf support-bundle_linux_amd64.tar.gz
            chmod +x support-bundle
            sudo mv support-bundle /usr/local/bin/

      # Verify the CLI installation
      - run:
          name: Verify Troubleshoot CLI
          command: |
            support-bundle --help

      # Prepare the Support Bundle
      - run:
          name: Prepare Support Bundle
          command: |
            mkdir -p support-bundle
            cp ./support-bundle-2.tar.gz support-bundle/

       # Debug Supported Flags
      - run:
          name: Check Available Flags
          command: |
            support-bundle analyze --help


      # Analyze the Support Bundle
      - run:
          name: Analyze Support Bundle
          command: |
            mkdir -p analysis-output
            support-bundle analyze support-bundle/support-bundle-2.tar.gz --output json > analysis-output/results.json



      # Store analysis results as artifacts
      - store_artifacts:
          path: analysis-output
          destination: support-bundle-analysis

workflows:
  version: 2
  support-bundle-analysis:
    jobs:
      - analyze-support-bundle
