version: 2.1

executors:
  troubleshoot-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/project

jobs:
  analyze-support-bundle:
    executor: troubleshoot-executor
    steps:
      - checkout

      # Access the support bundle file from the repo
      - run:
          name: Prepare Support Bundle
          command: |
            mkdir -p support-bundle
            cp ./support-bundle-2.tar.gz support-bundle/

      # Install the Troubleshoot CLI
      - run:
          name: Install Troubleshoot CLI
          command: |
            curl -LO https://github.com/replicatedhq/troubleshoot/releases/download/v0.114.0/collect_darwin_amd64.tar.gz
            chmod +x troubleshoot-linux-amd64
            mv troubleshoot-linux-amd64 /usr/local/bin/kubectl-support-bundle

      # Analyze the Support Bundle
      - run:
          name: Analyze Support Bundle
          command: |
            mkdir -p analysis-output
            kubectl-support-bundle analyze support-bundle/support-bundle.tar.gz --output-dir analysis-output

      # Store analysis results as artifacts
      - store_artifacts:
          path: analysis-output
          destination: support-bundle-analysis

workflows:
  version: 2
  support-bundle-analysis:
    jobs:
      - analyze-support-bundle
